name: Build and Release Arch Linux Kernel
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      REPO_DISPATCH_WEBHOOK_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: "Version string of kernel to build"
        required: true
        type: string
env:
  BUILD_VERSION: ${{ inputs.version }}
  REPO_DISPATCH_WEBHOOK_TOKEN: ${{ secrets.REPO_DISPATCH_WEBHOOK_TOKEN }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up for extra space
        run: |
          df -h /
          docker system prune -f || true
          sudo rm -rf \
              "$AGENT_TOOLSDIRECTORY" \
              /opt/google/chrome \
              /opt/microsoft/msedge \
              /opt/microsoft/powershell \
              /opt/pipx \
              /usr/lib/mono \
              /usr/local/julia* \
              /usr/local/lib/android \
              /usr/local/lib/node_modules \
              /usr/local/share/chromium \
              /usr/local/share/powershell \
              /usr/share/dotnet \
              /usr/share/swift
          df -h /
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Clone Arch Linux packaging repository
        run: |
          git clone https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git/ ./workspace/linux
      - name: Check-out Arch Linux packaging repository
        working-directory: ./workspace/linux
        run: |
          git checkout "$BUILD_VERSION"
      - name: Apply patches
        run: |
          ./patches/apply
      - name: Fix permission
        run: |
          find . -type f -exec chmod a+rw {} \;
          find . -type d -exec chmod a+rwx {} \;
      - name: Setup Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Setup Python dependencies
        run: |
          pip3 install -r ./script/requirements.txt
      - name: Run build script
        run: |
          python3 ./script/main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}
          path: ./workspace/linux/linux-*${{ inputs.version }}*.pkg.*
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Update last-built tag
        run: |
          echo "$BUILD_VERSION" >last-built
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "GitHub Actions: Update `last-built` tag"
          branch: actions/update-last-built-tag
          delete-branch: true
          branch-suffix: short-commit-hash
          title: "GitHub Actions: Update `last-built` tag"
          body: Update tag content to ${{ inputs.version }}
          assignees: |
            wxx9248
          reviewers: |
            wxx9248
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          automatic_release_tag: latest
          files: artifacts/${{ inputs.version }}/linux-*${{ inputs.version }}*.pkg.*
      - name: Call webhook to update repository
        run: |
          curl -L -f \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $REPO_DISPATCH_WEBHOOK_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"event_type\": \"Build and Publish Repository (triggered by $REPOSITORY_NAME)\"}" \
            https://api.github.com/repos/wxx9248/repo.wxx9248.top/dispatches
